### ISSUE TITLE
Just Not Working

### ISSUE THREAD

**Issue by juanlee8205** [aws-samples/aws-step-functions-kendra-web-crawler-search-engine#1]

**Comment by cogwirrel** [comment]
Hi @juanlee8205,

Sorry to hear this sample isn't working for you!

I wondered if you might be able to provide a little more detail?

Thanks,
Jack

**Comment by cogwirrel** [comment]
Unfortunately I don't think there's enough to go on here! Please reopen if you're able to provide a bit more detail so I can help you out! :)
