### ISSUE TITLE
Troubleshooting deploy

### ISSUE THREAD

**Issue by gerard-pml** [aws-samples/aws-step-functions-kendra-web-crawler-search-engine#21]
Hello,
I am learning TS and AWS. I really enjoyed your article about this project and wanted to try it out for a project I am working on. I tried installing this project on AWS, but ran into some minor issues. 

First, some packages appear to be depreciated. Example from my output:

**npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated puppeteer@10.1.0: Version no longer supported. Upgrade to @latest**

Also, I followed your instructions as well as the AWS documentation on bootstrapping, but still ran into an issue with my security token. For example, here is my output:

**WebCrawlerStack failed: InvalidClientTokenId: The security token included in the request is invalid
    at Request.extractError** 

I appreciate any insight you can provide.

**Comment by cogwirrel** [comment]
Hello! Ah that's great to hear you enjoyed the blog post!

Thanks for raising this! Re the deprecated packages, it may take some time to upgrade puppeteer as it's a little fiddly getting it to package correctly for a lambda function. I hope to address this soon but can't make any promises as to when unfortunately!

To unblock you though the security token issue might be related to your local AWS credentials? You may need to run `aws configure` and set up your access key, secret key and optional session token for the AWS account you wish to deploy the sample in?

Let me know if this helps! :)

Thanks,
Jack

**Comment by gerard-pml** [comment]
Hello Jack,

Thank you for your response! No worries about the timing for upgrading
puppeteer.
Regarding the security token, I have run aws configure for programmatic
access created in IAM. I think I'm doing something wrong when following the
AWS documentation on bootstrapping. It seems that your deploy script for
the project uses the CDK_PROFILE environment variable, which isn't created
for me when I follow the bootstrap documentation. Would you happen to know
of other documentation/tutorials that could help me with this issue?

Thanks again for your help,
Gerard

**Comment by cogwirrel** [comment]
Hi Gerard,

Ah so the CDK_PROFILE environment variable should be set to `default` by the `deploy` script unless you specify a `--profile` argument. Perhaps there's something strange with that default case?

Perhaps you could try `aws configure --profile webcrawler` to set up your credentials, and then run `./deploy --profile webcrawler`?

Hope that helps!

Thanks,
Jack

**Comment by gerard-pml** [comment]
Thank you!
I was able to get the step function to run and execute successfully by
configuring the profile and credentials as you suggested. It completed my
first crawl incredibly quickly. One question, if I didn't configure with
Kendra for my first run, so it seems that there is no output from the crawl
in the DynamoDB. I just have an empty table in the DB. Is that correct and
I should therefore configure with Kendra if I want an output from the crawl?
Thanks again for your help,
Gerard

**Comment by cogwirrel** [comment]
That's great to hear! 😄 

Yes you're right that this sample only writes the crawled content to S3 if the Kendra stack was deployed too. If you'd just like to write to S3 without Kendra (as Kendra can be costly if left running for long periods of time), you could always modify your copy of the code - the simplest would be to just hardcode an S3 destination for your chosen bucket here:

https://github.com/aws-samples/aws-step-functions-kendra-web-crawler-search-engine/blob/99b7cffdd05aa6a6ffcce0fb60828d78163ee2a1/src/lambda/steps/3_crawlPageAndQueueUrls.ts#L40-L44

The DynamoDB crawl history table should only contain metadata about executed crawls, such as the start/end times and total number of urls visited. It's a bit strange if that's completely empty - there shouldn't be any extracted content in there but there should be some metadata. Is that what you're seeing? :)

**Comment by gerard-pml** [comment]
Hi Jack,

Thanks again for your help. Indeed, the DynamoDB does hold the metadata
history of the crawl. I just wasn't looking in the right place.
Regarding saving to an S3 bucket, I'm also having a little trouble with
that. This is what I tried, but didn't get anything in my S3 bucket:

const destination = 'scraping-test' ? {
s3,
s3BucketName: 'scraping-test',
s3KeyPrefix: '/test/,
} : undefined;

**Comment by cogwirrel** [comment]
Hi Gerard,

Ooh I forgot to mention you'll also need to grant permissions for the crawl lambda to write to your s3 bucket - perhaps that's the issue? If you find the "CrawlPageAndQueueUrlsLambda" lambda function and then from there find its IAM role, you can try adding `s3:PutObject` permissions for objects in your bucket.

It might also be worth keeping the `s3KeyPrefix` as `crawlName` - the `/` at the front of `/test/` could possibly cause issues?

To pinpoint the issue, you can also take a look in a couple of places:

* The step functions state machine execution for the crawl - you can check if any steps were executed or if any steps failed
* The lambda logs in cloudwatch, particularly those for the "CrawlPageAndQueueUrlsLambda" - that could potentially have an error message or at least show whether page content was written to s3 or not.

Hope that helps! Let me know how you get on! :)

Cheers,
Jack

**Comment by PO-VINCENT** [comment]
Hi Jack,

When I tried to deploy the repo, this error keep happen. 

![1051688607613_ pic](https://github.com/aws-samples/aws-step-functions-kendra-web-crawler-search-engine/assets/33392655/698e6569-cfc9-4feb-8c99-fef734098b7e)

And I tried to fixed this issue by methods in https://stackoverflow.com/questions/66565550/how-to-solve-cdk-cli-version-mismatch/66578813#66578813, but still no use.

Could you help me out?

Thanks,
Vincent

**Comment by cogwirrel** [comment]
Hi Vincent,

Sorry to hear you're having issues deploying the sample!

It looks like I merged a dependabot PR which upgraded `aws-cdk-lib` but it did not upgrade `aws-cdk` to match!

I'll fix this shortly - thanks for raising this!

Thanks,
Jack

**Comment by cogwirrel** [comment]
I've updated `aws-cdk` to match and have verified a deployment on my end :)

Please could you try pulling the latest changes and redeploying and let me know how you get on?

Thanks again,
Jack
