### ISSUE TITLE
Using Distributed Map state to speed up the crawling process for large websites

### ISSUE THREAD

**Issue by philiptran** [aws-samples/aws-step-functions-kendra-web-crawler-search-engine#24]
@cogwirrel, first of all thank you for the great blog post and the sample code base for this Serverless web crawler stack. I have used this solution as an alternative to the Kendra web crawling connector which failed to crawl certain websites with unclear reasons.

When crawling large websites of tens or hundreds of thousands of links, the process took a long time due to the Inline Map state limit of 40 concurrent iterations. As discussed, I'm proposing to change the code base to use the new Distributed Map state that can support a maximum concurrency of up to 10,000 executions in parallel to speed up the crawling process.

**Comment by cogwirrel** [comment]
Great plan! 100% onboard with using a distributed map - thanks for the PR! 🚀
